### ISSUE TITLE
Scroll to top overlap

### ISSUE THREAD

**Issue by zigomir** [celtra/stateless-components#73]
If there's no metadata (because metadata is of gray color) and label takes whole width, `SCROLL TO TOP` button is barely visible:

![scroll-top-overlap](https://user-images.githubusercontent.com/957321/46051345-ca61f680-c0ed-11e8-8bef-cea0cf9efbe4.png)

Even if that is by design, it's not optimal and we should fix it.

/cc @kirill-celtra 
This was discovered while testing https://celtra.atlassian.net/browse/MAB-14108

@andrejventa are you the go–to person regarding component design or should I ask somebody else?

**Comment by andrejventa** [comment]
Hi, this issue was due to improper implementation of the component. I've since notified the dashboard team and they've implemented the fix [see monostack](https://sandbox.monostack-aleskurent.celtra-test.com/reports/#sharedKey=67eaf35829ffaa2def32160baefb229a).

The design for the component can be seen on [invision here](https://celtra.invisionapp.com/share/SFA5AGG7B#/319511784_Filter_-_Async)

**Comment by zigomir** [comment]
@andrejventa cool, thanks! @kurent please let me know when these changes are in master here so we update campaign explorer accordingly.

**Comment by kurent** [comment]
@zan-kusterle can you check where was this fix implemented?
